name: cv-pdf

on:
  pull_request:
  push:
    branches:
      - main

# Use bash by default in all jobs
defaults:
  run:
    # The -l {0} is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    shell: bash -l {0}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup caching for tectonic
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: tectonic-${{ runner.os }}

      - name: Setup caching for conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: environment.yml
          activate-environment: cv
          miniforge-variant: Mambaforge
          miniforge-version: "latest"
          use-mamba: true
          channel-priority: strict
          # Needed for caching
          use-only-tar-bz2: true

      - name: List installed packages
        run: mamba list

      - name: Compile the PDF
        run: |
          make
          touch output/
          cp *.pdf output/
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          
